require("dotenv").config();
const express = require("express");
const cors = require("cors");
const axios = require("axios");

const app = express();
const PORT = 3000;
app.use(cors());
app.use(express.json());

// ---- Google Generative AI ----
const {
  GoogleGenerativeAI,
  HarmCategory,
  HarmBlockThreshold,
} = require("@google/generative-ai");

const apiKey = process.env.GEMINI_API_KEY;
const genAI = new GoogleGenerativeAI(apiKey);

const model = genAI.getGenerativeModel({
  model: "gemini-2.0-flash",
  systemInstruction: "You are an insurance consultant, and the year is 2025. The chat will begin with you introducing yourself - you should begin by saying \"Hello my name is Tina, I can help you choose the right insurance policy. May I ask you a few personal questions to make sure I recommend the best policy for you?\". Do not ask the user what insurance product they want, instead you should ask a series of relevant questions and provide a recommendation to the user about what insurance policy to utilise, either mechanical breakdown insurance (MBI), comprehensive car insurance, or third party car insurance. Ask only one question at a time. \n\nMechanical Breakdown Insurance covers the costs of repairing your car that arises from a mechanical breakdown. The policy provides a guarantee for automotive machinery and electronic faults. MBI is not available to trucks and racing cars. For high-end vehicles, particularly European models like BMWs, Audis, or Volkswagens, MBI can be invaluable. For everyday cars, such as Toyotas, Hondas, or Mazdas, MBI is arguably less valuable.\n\nComprehensive car insurance specifically covers you if your car is stolen or damaged in an accident. It also pays out to other people if your car damages their vehicle or property. Comprehensive Car Insurance is only available to motor vehicles less than 10 years old, and is a popular choice for a vehicle worth more than $5,000. \n\nThird party car insurance only pays out to others, but does not cover your own car. This means if your car is stolen or involved in an accident, anyone affected other than you will be covered.\n\n Upon giving a recommendation do not ask any further questions, however if the user asks for a comparison please give one.",
});

const generationConfig = {
  temperature: 1,
  topP: 0.95,
  topK: 40,
  maxOutputTokens: 8192,
  responseMimeType: "text/plain",
};


app.post("/chat", async (req, res) => {
  /** Read the request data. */
  const chatHistory = req.body.history || [];
  const msg = req.body.chat;

  console.log("User input", msg); //log the user chat input

  /** Initialize the chat with the chat history and predefined parts */

  const fullChat = [
    ...chatHistory, // Add the chat history to the chat
    { role: "user", parts: [{ text: msg }] },
  ];

  const result = await model.generateContent({
    contents: fullChat,
    generationConfig,
  });

  /** Send the message posted by the user to the Gemini model and read the response generated by the model.*/

  const response = await result.response;
  const text = response.text();

  /** Send the response returned by the model as the API's response. */
  res.send({ text: text });

  console.log(result.response.text());
});


app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
